Trying to use common types package

diff --git a/apis/Dockerfile b/apis/Dockerfile
--- a/apis/Dockerfile
+++ b/apis/Dockerfile
@@ -1,9 +1,11 @@
 FROM golang:1.19 AS builder
 WORKDIR /app
-COPY go.mod go.sum ./
-RUN go mod download
-COPY apis.go dbutil.go apis_utils.go ./
-RUN CGO_ENABLED=1 GOOS=linux go build -o apis apis.go apis_utils.go dbutil.go
+
+COPY . .
+RUN ls -l /app && echo "Listing complete" || echo "Error listing /app"
+
+RUN go mod tidy
+RUN go build -o apis ./apis
 
 FROM debian:bookworm-slim
 WORKDIR /app
